dependencies:
- name: cp-kafka
  version: 0.1.0
  repository: "file://sub-charts/cp-kafka"
  condition: cp-kafka.enabled
- name: cp-zookeeper
  version: 0.1.0
  repository: "file://sub-charts/cp-zookeeper"
  condition: cp-zookeeper.enabled
- name: cp-schema-registry
  version: 0.1.0
  repository: "file://sub-charts/cp-schema-registry"
  condition: cp-schema-registry.enabled
- name: cp-kafka-rest
  version: 0.1.0
  repository: "file://sub-charts/cp-kafka-rest"
  condition: cp-kafka-rest.enabled
- name: cp-kafka-connect
  version: 0.1.0
  repository: "file://sub-charts/cp-kafka-connect"
  condition: cp-kafka-connect.enabled
- name: cp-ksql-server
  version: 0.1.0
  repository: "file://sub-charts/cp-ksql-server"
  condition: cp-ksql-server.enabled
