#!/usr/bin/env sh

BASEDIR=$(dirname $0)
ROOTDIR=$BASEDIR/..

rm $ROOTDIR/*tgz 2>/dev/null || true
rm -rf $ROOTDIR/charts 2>/dev/null || true
ls $ROOTDIR/sub-charts | xargs -I % rm -rf $ROOTDIR/sub-charts/%/charts 2>/dev/null || true
